[package]
name = "wcensor"
version = "0.1.1"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dmytro.kr@obox.systems>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/wcensor"
repository = "https://github.com/Wandalen/wTools/tree/master/module/core/wcensor"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/core/wcensor"
description = """
Utility to operate files from a command line.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

[lints]
workspace = true

[package.metadata.docs.rs]
features = [ "full" ]
all-features = false
exclude = [ "/tests", "/examples", "-*" ]
include = [
  "/rust/impl/censor",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[features]
default = [ "enabled" ]
full = [ "enabled" ]
# use_std = []
no_std = []
use_alloc = []
enabled = []

[lib]
name = "wcensor"
path = "src/censor/censor_lib.rs"

[[bin]]
name = "wcensor"
path = "src/censor/censor_entry.rs"

[[test]]
name = "censor_test"
path = "tests/censor/censor_tests.rs"

[[test]]
name = "censor_smoke_test"
path = "tests/smoke_test.rs"

# [[example]]
# name = "censor_trivial"
# path = "examples/censor_trivial/src/main.rs"

[dependencies]
wtools = { workspace = true }
error_tools ={ workspace = true }
meta_tools = { workspace = true, features = [ "full" ] }

[dev-dependencies]
test_tools = { workspace = true }
