[package]
name = "willbe"
version = "0.2.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dmytro.kr@obox.systems>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/willbe"
repository = "https://github.com/Wandalen/wTools/tree/master/module/move/willbe"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/move/willbe"
description = """
Utility with set of tools for managing developer routines.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

[lints]
workspace = true

[package.metadata.docs.rs]
features = [ "full" ]
all-features = false
exclude = [ "/tests", "/examples", "-*" ]

[features]
default = [ "enabled" ]
full = [ "enabled" ]
no_std = []
use_alloc = []
enabled = []

[dependencies]
mod_interface = { workspace = true, features = [ "default" ] }
error_tools = { workspace = true, features = [ "default" ] }
wca = { workspace = true, features = [ "default" ] }
former = { workspace = true, features = [ "default" ] }
anyhow = "~1.0"
toml_edit = "~0.14"
cargo_metadata = "~0.14"
ureq = "~2.4"
sha-1 = "~0.10"
globwalk = "~0.8"
petgraph = "~0.6"
ptree = "~0.4"
convert_case = "0.6.0"
lazy_static = "1.4.0"
regex = "1.10.2"

[dev-dependencies]
test_tools = { workspace = true }
assert_fs = "1.0"

[health.table]
stable_status = "experimental"
