[package]
name = "unitore"
version = "0.1.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>"
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/unitore"
description = """
Feed reader with the ability to set updates frequency.
"""
categories = [ "development-tools" ]
keywords = [ "rss-feed", "atom-feed" ]

[lints]
workspace = true

[package.metadata.docs.rs]
features = [ "full" ]

[features]
default = [
  "enabled",
]
full = [
  "enabled",
]
enabled = []

[dependencies]
tokio = { version = "1.36.0", features = [ "rt", "rt-multi-thread", "io-std", "macros" ] }
hyper = { version = "1.1.0", features = [ "full" ] }
hyper-tls = "0.6.0"
hyper-util = { version = "0.1", features = [ "full" ] }
http-body-util = "0.1"
feed-rs = "1.4.0"

[dev-dependencies]
test_tools = { workspace = true }
