[workspace]
resolver = "2"
members = [
    "module/*",
]

exclude = [
    "-*",
]

[workspace.metadata]
project_name = "{{name}}"
# your master branch (main or master)
master_branch = "{{mranch}}"
# url to project_repositiry
repo_url = "{{url}}"
# branches (includes master branch)
branches = [{ { branches } } ]

[workspace.lints.rust]
rust_2018_idioms = "deny"
missing_docs = "deny"
missing_debug_implementations = "deny" # opt out where Debug is really redundant
future_incompatible = "deny"

[workspace.lints.clippy]
restriction = "deny" # opt out where this is redundant
pedantic = "deny" # opt out where this is redundant