[package]
name = "former"
version = "0.8.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dmytro.kr@obox.systems>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/former"
repository = "https://github.com/Wandalen/wTools/tree/master/module/core/former"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/core/former"
description = """
A flexible and extensible implementation of the builder pattern.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose", "builder-pattern" ]

[lints]
workspace = true

[package.metadata.docs.rs]
features = [ "full" ]
all-features = false
exclude = [ "/tests", "-*" ]
# exclude = [ "/tests", "/examples", "-*" ]
# xxx : replicate for all modules

[features]

default = [ "enabled", "derive_former", "derive_component_from" ]
full = [ "enabled", "derive_former", "derive_component_from" ]
enabled = [ "former_meta/enabled" ]
no_std = []
use_alloc = []

derive_former = [ "former_meta/derive_former" ]
derive_component_from = [ "former_meta/derive_component_from" ]

[dependencies]
former_meta = { workspace = true }

[dev-dependencies]
test_tools = { workspace = true, features = [ "full" ] }
