[package]
name = "crates_tools"
version = "0.1.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/template_blank"
repository = "https://github.com/Wandalen/wTools/tree/master/module/core/template_blank"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/core/template_blank"
description = """
Crates tools
"""
categories = []
keywords = []

[lints]
workspace = true

[package.metadata.docs.rs]
features = [ "full" ]
all-features = false

[features]
default = [ "enabled" ]
full = [ "enabled" ]
no_std = []
use_alloc = []
enabled = [ "network" ]
network = [ "ureq" ]

[dependencies]
flate2 = "~1.0"
tar = "~0.4"
ureq = {  version = "~2.4", optional = true }

[dev-dependencies]
test_tools = { workspace = true }
