[[config]]
name = "bbc" 
update_period = "1min" 
link = "https://feeds.bbci.co.uk/news/world/rss.xml"

[[config]]
name = "times"
update_period = "1min"
link = "https://rss.nytimes.com/services/xml/rss/nyt/World.xml"
