name : data_type

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # data_type

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@alpha
    with :
      manifest_path : 'module/core/data_type/Cargo.toml'
      module_path: 'module/core/data_type/'
      module_name : 'data_type'
      commit_message : ${{ github.event.head_commit.message }}
