name : refiner

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # refiner

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@alpha
    with :
      manifest_path : 'module/move/refiner/Cargo.toml'
      module_path: 'module/move/refiner/'
      module_name : 'refiner'
      commit_message : ${{ github.event.head_commit.message }}
