name : proc_macro_tools

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # proc_macro_tools

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@alpha
    with :
      manifest_path : 'module/alias/proc_macro_tools/Cargo.toml'
      module_path: 'module/alias/proc_macro_tools/'
      module_name : 'proc_macro_tools'
      commit_message : ${{ github.event.head_commit.message }}
