name : type_constructor

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # type_constructor

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@alpha
    with :
      manifest_path : 'module/core/type_constructor/Cargo.toml'
      module_path: 'module/core/type_constructor/'
      module_name : 'type_constructor'
      commit_message : ${{ github.event.head_commit.message }}
