name : implements

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # implements

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@alpha
    with :
      manifest_path : 'module/core/implements/Cargo.toml'
      module_path: 'module/core/implements/'
      module_name : 'implements'
      commit_message : ${{ github.event.head_commit.message }}
