name : proper_tools

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # proper_tools

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@alpha
    with :
      manifest_path : 'module/alias/proper_tools/Cargo.toml'
      module_name : 'proper_tools'
      commit_message : ${{ github.event.head_commit.message }}
