name : optimization_tools

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # optimization_tools

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@alpha
    with :
      manifest_path : 'module/move/optimization_tools/Cargo.toml'
      module_path: 'module/move/optimization_tools/'
      module_name : 'optimization_tools'
      commit_message : ${{ github.event.head_commit.message }}
